In [1]:
import polars as pl
from pathlib import Path
from pprint import pprint

In [2]:
df_test = pl.DataFrame({"name": ["Alice", "Bob"]})
print(df_test["name"][0])
print(len(df_test["name"][0]))

Alice
5

In [3]:
DATA_DIR = Path("data/raw").resolve()

INGESTION_TABLES = [
    "Application.Countries.csv",
    "Application.StateProvinces.csv",
    "Application.Cities.csv",
    "Sales.CustomerCategories.csv",
    "Sales.BuyingGroups.csv",
    "Application.People.csv",
    "Warehouse.Colors.csv",
    "Warehouse.PackageTypes.csv",
    "Warehouse.StockItems.csv",
    "Sales.Customers.csv",
    "Sales.Orders.csv",
    "Sales.OrderLines.csv",
    "Sales.Invoices.csv",
    "Sales.InvoiceLines.csv"
]

In [4]:
def load_data(data_path: Path):
    if not data_path.exists():
        raise FileNotFoundError(f"Missing required source file: {data_path}")

    df = pl.read_csv(
        data_path,
        separator=";",
        null_values=["", "NULL", "N/A", "null", "None"],
        ignore_errors=True
    )

    return df

In [5]:
data_path = DATA_DIR / INGESTION_TABLES[0]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Application.Countries.csv
(190, 7)
shape: (5, 7)
┌───────────┬─────────────┬──────────────────────────┬──────────────────────────┬───────────┬────────┬─────────────────┐
│ CountryID ┆ CountryName ┆ FormalName               ┆ LatestRecordedPopulation ┆ Continent ┆ Region ┆ Subregion       │
│ ---       ┆ ---         ┆ ---                      ┆ ---                      ┆ ---       ┆ ---    ┆ ---             │
│ i64       ┆ str         ┆ str                      ┆ i64                      ┆ str       ┆ str    ┆ str             │
╞═══════════╪═════════════╪══════════════════════════╪══════════════════════════╪═══════════╪════════╪═════════════════╡
│ 1         ┆ Afghanistan ┆ Islamic State of         ┆ 28400000                 ┆ Asia      ┆ Asia   ┆ Southern Asia   │
│           ┆             ┆ Afghanistan              ┆                          ┆           ┆        ┆                 │
│ 3         ┆ Albania     ┆ Republic of Albania      ┆ 3785031                  ┆ Europe    ┆ Europe ┆ Southern Europe │
│ 4         ┆ Algeria     ┆ People's Democratic      ┆ 34178188                 ┆ Africa    ┆ Africa ┆ Northern Africa │
│           ┆             ┆ Republic o…              ┆                          ┆           ┆        ┆                 │
│ 6         ┆ Andorra     ┆ Principality of Andorra  ┆ 87243                    ┆ Europe    ┆ Europe ┆ Southern Europe │
│ 7         ┆ Angola      ┆ People's Republic of     ┆ 12799293                 ┆ Africa    ┆ Africa ┆ Middle Africa   │
│           ┆             ┆ Angola                   ┆                          ┆           ┆        ┆                 │
└───────────┴─────────────┴──────────────────────────┴──────────────────────────┴───────────┴────────┴─────────────────┘
[{'CountryID': 0,
  'CountryName': 0,
  'FormalName': 0,
  'LatestRecordedPopulation': 0,
  'Continent': 0,
  'Region': 0,
  'Subregion': 0}]

In [6]:
data_path = DATA_DIR / INGESTION_TABLES[1]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Application.StateProvinces.csv
(53, 6)
shape: (5, 6)
┌─────────────────┬───────────────────┬───────────────────┬───────────┬────────────────┬──────────────────────────┐
│ StateProvinceID ┆ StateProvinceCode ┆ StateProvinceName ┆ CountryID ┆ SalesTerritory ┆ LatestRecordedPopulation │
│ ---             ┆ ---               ┆ ---               ┆ ---       ┆ ---            ┆ ---                      │
│ i64             ┆ str               ┆ str               ┆ i64       ┆ str            ┆ i64                      │
╞═════════════════╪═══════════════════╪═══════════════════╪═══════════╪════════════════╪══════════════════════════╡
│ 1               ┆ AL                ┆ Alabama           ┆ 230       ┆ Southeast      ┆ 5437278                  │
│ 2               ┆ AK                ┆ Alaska            ┆ 230       ┆ Far West       ┆ 735132                   │
│ 3               ┆ AZ                ┆ Arizona           ┆ 230       ┆ Southwest      ┆ 6891688                  │
│ 4               ┆ AR                ┆ Arkansas          ┆ 230       ┆ Southeast      ┆ 3077747                  │
│ 5               ┆ CA                ┆ California        ┆ 230       ┆ Far West       ┆ 41460453                 │
└─────────────────┴───────────────────┴───────────────────┴───────────┴────────────────┴──────────────────────────┘
[{'StateProvinceID': 0,
  'StateProvinceCode': 0,
  'StateProvinceName': 0,
  'CountryID': 0,
  'SalesTerritory': 0,
  'LatestRecordedPopulation': 0}]

In [7]:
data_path = DATA_DIR / INGESTION_TABLES[2]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Application.Cities.csv
(37940, 6)
shape: (5, 6)
┌────────┬────────────┬─────────────────┬────────────┬─────────────┬──────────────────────────┐
│ CityID ┆ CityName   ┆ StateProvinceID ┆ Latitude   ┆ Longitude   ┆ LatestRecordedPopulation │
│ ---    ┆ ---        ┆ ---             ┆ ---        ┆ ---         ┆ ---                      │
│ i64    ┆ str        ┆ i64             ┆ str        ┆ str         ┆ i64                      │
╞════════╪════════════╪═════════════════╪════════════╪═════════════╪══════════════════════════╡
│ 1      ┆ Aaronsburg ┆ 39              ┆ 40,8997903 ┆ -77,4533235 ┆ 613                      │
│ 3      ┆ Abanda     ┆ 1               ┆ 33,100954  ┆ -85,5296753 ┆ 192                      │
│ 4      ┆ Abbeville  ┆ 42              ┆ 34,1781719 ┆ -82,3790148 ┆ 5237                     │
│ 5      ┆ Abbeville  ┆ 11              ┆ 31,9921223 ┆ -83,3068243 ┆ 2908                     │
│ 6      ┆ Abbeville  ┆ 1               ┆ 31,5718352 ┆ -85,2504893 ┆ 2688                     │
└────────┴────────────┴─────────────────┴────────────┴─────────────┴──────────────────────────┘
[{'CityID': 0,
  'CityName': 0,
  'StateProvinceID': 0,
  'Latitude': 0,
  'Longitude': 0,
  'LatestRecordedPopulation': 11048}]

In [8]:
data_path = DATA_DIR / INGESTION_TABLES[3]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.CustomerCategories.csv
(8, 2)
shape: (5, 2)
┌────────────────────┬──────────────────────┐
│ CustomerCategoryID ┆ CustomerCategoryName │
│ ---                ┆ ---                  │
│ i64                ┆ str                  │
╞════════════════════╪══════════════════════╡
│ 1                  ┆ Agent                │
│ 2                  ┆ Wholesaler           │
│ 3                  ┆ Novelty Shop         │
│ 4                  ┆ Supermarket          │
│ 5                  ┆ Computer Store       │
└────────────────────┴──────────────────────┘
[{'CustomerCategoryID': 0, 'CustomerCategoryName': 0}]

In [9]:
data_path = DATA_DIR / INGESTION_TABLES[4]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.BuyingGroups.csv
(2, 2)
shape: (2, 2)
┌───────────────┬─────────────────┐
│ BuyingGroupID ┆ BuyingGroupName │
│ ---           ┆ ---             │
│ i64           ┆ str             │
╞═══════════════╪═════════════════╡
│ 1             ┆ Tailspin Toys   │
│ 2             ┆ Wingtip Toys    │
└───────────────┴─────────────────┘
[{'BuyingGroupID': 0, 'BuyingGroupName': 0}]

In [10]:
data_path = DATA_DIR / INGESTION_TABLES[5]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Application.People.csv
(1111, 6)
shape: (5, 6)
┌──────────┬──────────────────────┬──────────────────────┬───────────────────────────┬────────────┬───────────────┐
│ PersonID ┆ FullName             ┆ PreferredName        ┆ SearchName                ┆ IsEmployee ┆ IsSalesperson │
│ ---      ┆ ---                  ┆ ---                  ┆ ---                       ┆ ---        ┆ ---           │
│ i64      ┆ str                  ┆ str                  ┆ str                       ┆ i64        ┆ i64           │
╞══════════╪══════════════════════╪══════════════════════╪═══════════════════════════╪════════════╪═══════════════╡
│ 1        ┆ Data Conversion Only ┆ Data Conversion Only ┆ Data Conversion Only Data ┆ 0          ┆ 0             │
│          ┆                      ┆                      ┆ Conv…                     ┆            ┆               │
│ 2        ┆ Kayla Woodcock       ┆ Kayla                ┆ Kayla Kayla Woodcock      ┆ 1          ┆ 1             │
│ 3        ┆ Hudson Onslow        ┆ Hudson               ┆ Hudson Hudson Onslow      ┆ 1          ┆ 1             │
│ 4        ┆ Isabella Rupp        ┆ Isabella             ┆ Isabella Isabella Rupp    ┆ 1          ┆ 0             │
│ 5        ┆ Eva Muirden          ┆ Eva                  ┆ Eva Eva Muirden           ┆ 1          ┆ 0             │
└──────────┴──────────────────────┴──────────────────────┴───────────────────────────┴────────────┴───────────────┘
[{'PersonID': 0,
  'FullName': 0,
  'PreferredName': 0,
  'SearchName': 0,
  'IsEmployee': 0,
  'IsSalesperson': 0}]

In [11]:
data_path = DATA_DIR / INGESTION_TABLES[6]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Warehouse.Colors.csv
(36, 2)
shape: (5, 2)
┌─────────┬───────────┐
│ ColorID ┆ ColorName │
│ ---     ┆ ---       │
│ i64     ┆ str       │
╞═════════╪═══════════╡
│ 1       ┆ Azure     │
│ 2       ┆ Beige     │
│ 3       ┆ Black     │
│ 4       ┆ Blue      │
│ 5       ┆ Charcoal  │
└─────────┴───────────┘
[{'ColorID': 0, 'ColorName': 0}]

In [12]:
data_path = DATA_DIR / INGESTION_TABLES[7]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Warehouse.PackageTypes.csv
(14, 2)
shape: (5, 2)
┌───────────────┬─────────────────┐
│ PackageTypeID ┆ PackageTypeName │
│ ---           ┆ ---             │
│ i64           ┆ str             │
╞═══════════════╪═════════════════╡
│ 1             ┆ Bag             │
│ 2             ┆ Block           │
│ 3             ┆ Bottle          │
│ 4             ┆ Box             │
│ 5             ┆ Can             │
└───────────────┴─────────────────┘
[{'PackageTypeID': 0, 'PackageTypeName': 0}]

In [13]:
data_path = DATA_DIR / INGESTION_TABLES[8]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Warehouse.StockItems.csv
(227, 16)
shape: (5, 16)
┌─────────────┬──────────────────┬────────────┬─────────┬───┬─────────┬───────────┬──────────────────┬─────────────────┐
│ StockItemID ┆ StockItemName    ┆ SupplierID ┆ ColorID ┆ … ┆ TaxRate ┆ UnitPrice ┆ RecommendedRetai ┆ TypicalWeightPe │
│ ---         ┆ ---              ┆ ---        ┆ ---     ┆   ┆ ---     ┆ ---       ┆ lPrice           ┆ rUnit           │
│ i64         ┆ str              ┆ i64        ┆ i64     ┆   ┆ f64     ┆ f64       ┆ ---              ┆ ---             │
│             ┆                  ┆            ┆         ┆   ┆         ┆           ┆ f64              ┆ f64             │
╞═════════════╪══════════════════╪════════════╪═════════╪═══╪═════════╪═══════════╪══════════════════╪═════════════════╡
│ 1           ┆ USB missile      ┆ 12         ┆ null    ┆ … ┆ 15.0    ┆ 25.0      ┆ 37.38            ┆ 0.3             │
│             ┆ launcher (Green) ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 2           ┆ USB rocket       ┆ 12         ┆ 12      ┆ … ┆ 15.0    ┆ 25.0      ┆ 37.38            ┆ 0.3             │
│             ┆ launcher (Gray)  ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 3           ┆ Office cube      ┆ 12         ┆ 3       ┆ … ┆ 15.0    ┆ 18.5      ┆ 27.66            ┆ 0.25            │
│             ┆ periscope        ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│             ┆ (Black)          ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 4           ┆ USB food flash   ┆ 12         ┆ null    ┆ … ┆ 15.0    ┆ 32.0      ┆ 47.84            ┆ 0.05            │
│             ┆ drive - sushi r… ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 5           ┆ USB food flash   ┆ 12         ┆ null    ┆ … ┆ 15.0    ┆ 32.0      ┆ 47.84            ┆ 0.05            │
│             ┆ drive - hamburg… ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
└─────────────┴──────────────────┴────────────┴─────────┴───┴─────────┴───────────┴──────────────────┴─────────────────┘
[{'StockItemID': 0,
  'StockItemName': 0,
  'SupplierID': 0,
  'ColorID': 99,
  'UnitPackageID': 0,
  'OuterPackageID': 0,
  'Brand': 209,
  'Size': 64,
  'LeadTimeDays': 0,
  'QuantityPerOuter': 0,
  'IsChillerStock': 0,
  'Barcode': 219,
  'TaxRate': 0,
  'UnitPrice': 0,
  'RecommendedRetailPrice': 0,
  'TypicalWeightPerUnit': 0}]

In [14]:
df_test.head()

shape: (5, 16)
┌─────────────┬──────────────────┬────────────┬─────────┬───┬─────────┬───────────┬──────────────────┬─────────────────┐
│ StockItemID ┆ StockItemName    ┆ SupplierID ┆ ColorID ┆ … ┆ TaxRate ┆ UnitPrice ┆ RecommendedRetai ┆ TypicalWeightPe │
│ ---         ┆ ---              ┆ ---        ┆ ---     ┆   ┆ ---     ┆ ---       ┆ lPrice           ┆ rUnit           │
│ i64         ┆ str              ┆ i64        ┆ i64     ┆   ┆ f64     ┆ f64       ┆ ---              ┆ ---             │
│             ┆                  ┆            ┆         ┆   ┆         ┆           ┆ f64              ┆ f64             │
╞═════════════╪══════════════════╪════════════╪═════════╪═══╪═════════╪═══════════╪══════════════════╪═════════════════╡
│ 1           ┆ USB missile      ┆ 12         ┆ null    ┆ … ┆ 15.0    ┆ 25.0      ┆ 37.38            ┆ 0.3             │
│             ┆ launcher (Green) ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 2           ┆ USB rocket       ┆ 12         ┆ 12      ┆ … ┆ 15.0    ┆ 25.0      ┆ 37.38            ┆ 0.3             │
│             ┆ launcher (Gray)  ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 3           ┆ Office cube      ┆ 12         ┆ 3       ┆ … ┆ 15.0    ┆ 18.5      ┆ 27.66            ┆ 0.25            │
│             ┆ periscope        ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│             ┆ (Black)          ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 4           ┆ USB food flash   ┆ 12         ┆ null    ┆ … ┆ 15.0    ┆ 32.0      ┆ 47.84            ┆ 0.05            │
│             ┆ drive - sushi r… ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
│ 5           ┆ USB food flash   ┆ 12         ┆ null    ┆ … ┆ 15.0    ┆ 32.0      ┆ 47.84            ┆ 0.05            │
│             ┆ drive - hamburg… ┆            ┆         ┆   ┆         ┆           ┆                  ┆                 │
└─────────────┴──────────────────┴────────────┴─────────┴───┴─────────┴───────────┴──────────────────┴─────────────────┘

In [15]:
data_path = DATA_DIR / INGESTION_TABLES[9]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

# df_test.head()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.Customers.csv
(663, 20)
shape: (5, 20)
┌────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ CustomerID ┆ CustomerName ┆ BillToCustom ┆ CustomerCate ┆ … ┆ WebsiteURL   ┆ DeliveryAdd ┆ DeliveryLoc ┆ DeliveryLoc │
│ ---        ┆ ---          ┆ erID         ┆ goryID       ┆   ┆ ---          ┆ ressLine    ┆ ationLat    ┆ ationLong   │
│ i64        ┆ str          ┆ ---          ┆ ---          ┆   ┆ str          ┆ ---         ┆ ---         ┆ ---         │
│            ┆              ┆ i64          ┆ i64          ┆   ┆              ┆ str         ┆ str         ┆ str         │
╞════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 1877 Mittal ┆ 41,4972022  ┆ -102,620197 │
│            ┆ Toys (Head   ┆              ┆              ┆   ┆ ailspintoys. ┆ Road        ┆             ┆ 9           │
│            ┆ Office)      ┆              ┆              ┆   ┆ com          ┆             ┆             ┆             │
│ 2          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 705 Dita    ┆ 48,7163356  ┆ -115,874350 │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Lane        ┆             ┆ 7           │
│            ┆ (Sylvanite,  ┆              ┆              ┆   ┆ com/Sy…      ┆             ┆             ┆             │
│            ┆ MT)          ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
│ 3          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 1970        ┆ 34,2689145  ┆ -112,727122 │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Khandke     ┆             ┆ 3           │
│            ┆ (Peeples     ┆              ┆              ┆   ┆ com/Pe…      ┆ Road        ┆             ┆             │
│            ┆ Valley,…     ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
│ 4          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 967 Riutta  ┆ 37,2811339  ┆ -98,580361  │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Boulevard   ┆             ┆             │
│            ┆ (Medicine    ┆              ┆              ┆   ┆ com/Me…      ┆             ┆             ┆             │
│            ┆ Lodge,…      ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
│ 5          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 1674        ┆ 43,1992244  ┆ -78,5761394 │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Skujins     ┆             ┆             │
│            ┆ (Gasport,    ┆              ┆              ┆   ┆ com/Ga…      ┆ Boulevard   ┆             ┆             │
│            ┆ NY)          ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
└────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘
[{'CustomerID': 0,
  'CustomerName': 0,
  'BillToCustomerID': 0,
  'CustomerCategoryID': 0,
  'BuyingGroupID': 261,
  'PrimaryContactPersonID': 0,
  'AlternateContactPersonID': 261,
  'DeliveryMethodID': 0,
  'DeliveryCityID': 0,
  'CreditLimit': 402,
  'AccountOpenedDate': 0,
  'StandardDiscountPercentage': 0,
  'IsStatementSent': 0,
  'IsOnCreditHold': 0,
  'PaymentDays': 0,
  'PhoneNumber': 0,
  'WebsiteURL': 0,
  'DeliveryAddressLine': 0,
  'DeliveryLocationLat': 0,
  'DeliveryLocationLong': 0}]

In [16]:
df_test.head()

shape: (5, 20)
┌────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ CustomerID ┆ CustomerName ┆ BillToCustom ┆ CustomerCate ┆ … ┆ WebsiteURL   ┆ DeliveryAdd ┆ DeliveryLoc ┆ DeliveryLoc │
│ ---        ┆ ---          ┆ erID         ┆ goryID       ┆   ┆ ---          ┆ ressLine    ┆ ationLat    ┆ ationLong   │
│ i64        ┆ str          ┆ ---          ┆ ---          ┆   ┆ str          ┆ ---         ┆ ---         ┆ ---         │
│            ┆              ┆ i64          ┆ i64          ┆   ┆              ┆ str         ┆ str         ┆ str         │
╞════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 1877 Mittal ┆ 41,4972022  ┆ -102,620197 │
│            ┆ Toys (Head   ┆              ┆              ┆   ┆ ailspintoys. ┆ Road        ┆             ┆ 9           │
│            ┆ Office)      ┆              ┆              ┆   ┆ com          ┆             ┆             ┆             │
│ 2          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 705 Dita    ┆ 48,7163356  ┆ -115,874350 │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Lane        ┆             ┆ 7           │
│            ┆ (Sylvanite,  ┆              ┆              ┆   ┆ com/Sy…      ┆             ┆             ┆             │
│            ┆ MT)          ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
│ 3          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 1970        ┆ 34,2689145  ┆ -112,727122 │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Khandke     ┆             ┆ 3           │
│            ┆ (Peeples     ┆              ┆              ┆   ┆ com/Pe…      ┆ Road        ┆             ┆             │
│            ┆ Valley,…     ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
│ 4          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 967 Riutta  ┆ 37,2811339  ┆ -98,580361  │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Boulevard   ┆             ┆             │
│            ┆ (Medicine    ┆              ┆              ┆   ┆ com/Me…      ┆             ┆             ┆             │
│            ┆ Lodge,…      ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
│ 5          ┆ Tailspin     ┆ 1            ┆ 3            ┆ … ┆ http://www.t ┆ 1674        ┆ 43,1992244  ┆ -78,5761394 │
│            ┆ Toys         ┆              ┆              ┆   ┆ ailspintoys. ┆ Skujins     ┆             ┆             │
│            ┆ (Gasport,    ┆              ┆              ┆   ┆ com/Ga…      ┆ Boulevard   ┆             ┆             │
│            ┆ NY)          ┆              ┆              ┆   ┆              ┆             ┆             ┆             │
└────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [17]:
data_path = DATA_DIR / INGESTION_TABLES[10]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.Orders.csv
(73595, 11)
shape: (5, 11)
┌─────────┬────────────┬───────────────┬───────────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ OrderID ┆ CustomerID ┆ SalespersonPe ┆ PickedByPerso ┆ … ┆ ExpectedDeli ┆ CustomerPurc ┆ IsUndersuppl ┆ PickingCompl │
│ ---     ┆ ---        ┆ rsonID        ┆ nID           ┆   ┆ veryDate     ┆ haseOrderNum ┆ yBackordered ┆ etedWhen     │
│ i64     ┆ i64        ┆ ---           ┆ ---           ┆   ┆ ---          ┆ ber          ┆ ---          ┆ ---          │
│         ┆            ┆ i64           ┆ i64           ┆   ┆ str          ┆ ---          ┆ i64          ┆ str          │
│         ┆            ┆               ┆               ┆   ┆              ┆ i64          ┆              ┆              │
╞═════════╪════════════╪═══════════════╪═══════════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1       ┆ 832        ┆ 2             ┆ null          ┆ … ┆ 02/01/2013   ┆ 12126        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 2       ┆ 803        ┆ 8             ┆ null          ┆ … ┆ 02/01/2013   ┆ 15342        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 3       ┆ 105        ┆ 7             ┆ null          ┆ … ┆ 02/01/2013   ┆ 12211        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 4       ┆ 57         ┆ 16            ┆ 3             ┆ … ┆ 02/01/2013   ┆ 17129        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 11:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 5       ┆ 905        ┆ 3             ┆ null          ┆ … ┆ 02/01/2013   ┆ 10369        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
└─────────┴────────────┴───────────────┴───────────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘
[{'OrderID': 0,
  'CustomerID': 0,
  'SalespersonPersonID': 0,
  'PickedByPersonID': 10623,
  'ContactPersonID': 0,
  'BackorderOrderID': 66057,
  'OrderDate': 0,
  'ExpectedDeliveryDate': 0,
  'CustomerPurchaseOrderNumber': 0,
  'IsUndersupplyBackordered': 0,
  'PickingCompletedWhen': 3085}]

In [18]:
df_test.head()

shape: (5, 11)
┌─────────┬────────────┬───────────────┬───────────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ OrderID ┆ CustomerID ┆ SalespersonPe ┆ PickedByPerso ┆ … ┆ ExpectedDeli ┆ CustomerPurc ┆ IsUndersuppl ┆ PickingCompl │
│ ---     ┆ ---        ┆ rsonID        ┆ nID           ┆   ┆ veryDate     ┆ haseOrderNum ┆ yBackordered ┆ etedWhen     │
│ i64     ┆ i64        ┆ ---           ┆ ---           ┆   ┆ ---          ┆ ber          ┆ ---          ┆ ---          │
│         ┆            ┆ i64           ┆ i64           ┆   ┆ str          ┆ ---          ┆ i64          ┆ str          │
│         ┆            ┆               ┆               ┆   ┆              ┆ i64          ┆              ┆              │
╞═════════╪════════════╪═══════════════╪═══════════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1       ┆ 832        ┆ 2             ┆ null          ┆ … ┆ 02/01/2013   ┆ 12126        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 2       ┆ 803        ┆ 8             ┆ null          ┆ … ┆ 02/01/2013   ┆ 15342        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 3       ┆ 105        ┆ 7             ┆ null          ┆ … ┆ 02/01/2013   ┆ 12211        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 4       ┆ 57         ┆ 16            ┆ 3             ┆ … ┆ 02/01/2013   ┆ 17129        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 11:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
│ 5       ┆ 905        ┆ 3             ┆ null          ┆ … ┆ 02/01/2013   ┆ 10369        ┆ 1            ┆ 2013-01-01   │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 12:00:00.000 │
│         ┆            ┆               ┆               ┆   ┆              ┆              ┆              ┆ 0000         │
└─────────┴────────────┴───────────────┴───────────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [19]:
data_path = DATA_DIR / INGESTION_TABLES[11]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.OrderLines.csv
(231412, 10)
shape: (5, 10)
┌─────────────┬─────────┬─────────────┬──────────────────┬───┬───────────┬─────────┬────────────────┬──────────────────┐
│ OrderLineID ┆ OrderID ┆ StockItemID ┆ Description      ┆ … ┆ UnitPrice ┆ TaxRate ┆ PickedQuantity ┆ PickingCompleted │
│ ---         ┆ ---     ┆ ---         ┆ ---              ┆   ┆ ---       ┆ ---     ┆ ---            ┆ When             │
│ i64         ┆ i64     ┆ i64         ┆ str              ┆   ┆ f64       ┆ f64     ┆ i64            ┆ ---              │
│             ┆         ┆             ┆                  ┆   ┆           ┆         ┆                ┆ str              │
╞═════════════╪═════════╪═════════════╪══════════════════╪═══╪═══════════╪═════════╪════════════════╪══════════════════╡
│ 1           ┆ 45      ┆ 164         ┆ 32 mm Double     ┆ … ┆ 112.0     ┆ 15.0    ┆ 50             ┆ 2013-01-02       │
│             ┆         ┆             ┆ sided bubble     ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ wrap…            ┆   ┆           ┆         ┆                ┆                  │
│ 2           ┆ 1       ┆ 67          ┆ Ride on toy      ┆ … ┆ 230.0     ┆ 15.0    ┆ 10             ┆ 2013-01-01       │
│             ┆         ┆             ┆ sedan car        ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ (Black) …        ┆   ┆           ┆         ┆                ┆                  │
│ 3           ┆ 2       ┆ 50          ┆ Developer joke   ┆ … ┆ 13.0      ┆ 15.0    ┆ 9              ┆ 2013-01-01       │
│             ┆         ┆             ┆ mug - old C dev… ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│ 4           ┆ 46      ┆ 89          ┆ "The Gu" red     ┆ … ┆ 18.0      ┆ 15.0    ┆ 72             ┆ 2013-01-02       │
│             ┆         ┆             ┆ shirt XML tag    ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ t-s…             ┆   ┆           ┆         ┆                ┆                  │
│ 5           ┆ 46      ┆ 171         ┆ 32 mm Anti       ┆ … ┆ 32.0      ┆ 15.0    ┆ 90             ┆ 2013-01-02       │
│             ┆         ┆             ┆ static bubble    ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ wrap …           ┆   ┆           ┆         ┆                ┆                  │
└─────────────┴─────────┴─────────────┴──────────────────┴───┴───────────┴─────────┴────────────────┴──────────────────┘
[{'OrderLineID': 0,
  'OrderID': 0,
  'StockItemID': 0,
  'Description': 0,
  'PackageTypeID': 0,
  'Quantity': 0,
  'UnitPrice': 0,
  'TaxRate': 0,
  'PickedQuantity': 0,
  'PickingCompletedWhen': 3147}]

In [20]:
df_test.head()

shape: (5, 10)
┌─────────────┬─────────┬─────────────┬──────────────────┬───┬───────────┬─────────┬────────────────┬──────────────────┐
│ OrderLineID ┆ OrderID ┆ StockItemID ┆ Description      ┆ … ┆ UnitPrice ┆ TaxRate ┆ PickedQuantity ┆ PickingCompleted │
│ ---         ┆ ---     ┆ ---         ┆ ---              ┆   ┆ ---       ┆ ---     ┆ ---            ┆ When             │
│ i64         ┆ i64     ┆ i64         ┆ str              ┆   ┆ f64       ┆ f64     ┆ i64            ┆ ---              │
│             ┆         ┆             ┆                  ┆   ┆           ┆         ┆                ┆ str              │
╞═════════════╪═════════╪═════════════╪══════════════════╪═══╪═══════════╪═════════╪════════════════╪══════════════════╡
│ 1           ┆ 45      ┆ 164         ┆ 32 mm Double     ┆ … ┆ 112.0     ┆ 15.0    ┆ 50             ┆ 2013-01-02       │
│             ┆         ┆             ┆ sided bubble     ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ wrap…            ┆   ┆           ┆         ┆                ┆                  │
│ 2           ┆ 1       ┆ 67          ┆ Ride on toy      ┆ … ┆ 230.0     ┆ 15.0    ┆ 10             ┆ 2013-01-01       │
│             ┆         ┆             ┆ sedan car        ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ (Black) …        ┆   ┆           ┆         ┆                ┆                  │
│ 3           ┆ 2       ┆ 50          ┆ Developer joke   ┆ … ┆ 13.0      ┆ 15.0    ┆ 9              ┆ 2013-01-01       │
│             ┆         ┆             ┆ mug - old C dev… ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│ 4           ┆ 46      ┆ 89          ┆ "The Gu" red     ┆ … ┆ 18.0      ┆ 15.0    ┆ 72             ┆ 2013-01-02       │
│             ┆         ┆             ┆ shirt XML tag    ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ t-s…             ┆   ┆           ┆         ┆                ┆                  │
│ 5           ┆ 46      ┆ 171         ┆ 32 mm Anti       ┆ … ┆ 32.0      ┆ 15.0    ┆ 90             ┆ 2013-01-02       │
│             ┆         ┆             ┆ static bubble    ┆   ┆           ┆         ┆                ┆ 11:00:00.0000000 │
│             ┆         ┆             ┆ wrap …           ┆   ┆           ┆         ┆                ┆                  │
└─────────────┴─────────┴─────────────┴──────────────────┴───┴───────────┴─────────┴────────────────┴──────────────────┘

In [21]:
data_path = DATA_DIR / INGESTION_TABLES[12]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.Invoices.csv
(70510, 16)
shape: (5, 16)
┌───────────┬────────────┬───────────────┬─────────┬───┬───────────────┬───────────────┬───────────────┬───────────────┐
│ InvoiceID ┆ CustomerID ┆ BillToCustome ┆ OrderID ┆ … ┆ TotalDryItems ┆ TotalChillerI ┆ ConfirmedDeli ┆ ConfirmedRece │
│ ---       ┆ ---        ┆ rID           ┆ ---     ┆   ┆ ---           ┆ tems          ┆ veryTime      ┆ ivedBy        │
│ i64       ┆ i64        ┆ ---           ┆ i64     ┆   ┆ i64           ┆ ---           ┆ ---           ┆ ---           │
│           ┆            ┆ i64           ┆         ┆   ┆               ┆ i64           ┆ str           ┆ str           │
╞═══════════╪════════════╪═══════════════╪═════════╪═══╪═══════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 1         ┆ 832        ┆ 832           ┆ 1       ┆ … ┆ 1             ┆ 0             ┆ 2013-01-02    ┆ Aakriti       │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:05:00.0000 ┆ Byrraju       │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 2         ┆ 803        ┆ 803           ┆ 2       ┆ … ┆ 2             ┆ 0             ┆ 2013-01-02    ┆ Bala Dixit    │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:10:00.0000 ┆               │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 3         ┆ 105        ┆ 1             ┆ 3       ┆ … ┆ 1             ┆ 0             ┆ 2013-01-02    ┆ Sung-Hwan     │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:15:00.0000 ┆ Hwang         │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 4         ┆ 57         ┆ 1             ┆ 4       ┆ … ┆ 3             ┆ 0             ┆ 2013-01-02    ┆ Aile Mae      │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:20:00.0000 ┆               │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 5         ┆ 905        ┆ 905           ┆ 5       ┆ … ┆ 3             ┆ 0             ┆ 2013-01-02    ┆ Sara Huiting  │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:25:00.0000 ┆               │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
└───────────┴────────────┴───────────────┴─────────┴───┴───────────────┴───────────────┴───────────────┴───────────────┘
[{'InvoiceID': 0,
  'CustomerID': 0,
  'BillToCustomerID': 0,
  'OrderID': 0,
  'DeliveryMethodID': 0,
  'ContactPersonID': 0,
  'AccountsPersonID': 0,
  'SalespersonPersonID': 0,
  'PackedByPersonID': 0,
  'InvoiceDate': 0,
  'CustomerPurchaseOrderNumber': 0,
  'DeliveryInstructions': 0,
  'TotalDryItems': 0,
  'TotalChillerItems': 0,
  'ConfirmedDeliveryTime': 84,
  'ConfirmedReceivedBy': 84}]

In [22]:
df_test.head()

shape: (5, 16)
┌───────────┬────────────┬───────────────┬─────────┬───┬───────────────┬───────────────┬───────────────┬───────────────┐
│ InvoiceID ┆ CustomerID ┆ BillToCustome ┆ OrderID ┆ … ┆ TotalDryItems ┆ TotalChillerI ┆ ConfirmedDeli ┆ ConfirmedRece │
│ ---       ┆ ---        ┆ rID           ┆ ---     ┆   ┆ ---           ┆ tems          ┆ veryTime      ┆ ivedBy        │
│ i64       ┆ i64        ┆ ---           ┆ i64     ┆   ┆ i64           ┆ ---           ┆ ---           ┆ ---           │
│           ┆            ┆ i64           ┆         ┆   ┆               ┆ i64           ┆ str           ┆ str           │
╞═══════════╪════════════╪═══════════════╪═════════╪═══╪═══════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 1         ┆ 832        ┆ 832           ┆ 1       ┆ … ┆ 1             ┆ 0             ┆ 2013-01-02    ┆ Aakriti       │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:05:00.0000 ┆ Byrraju       │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 2         ┆ 803        ┆ 803           ┆ 2       ┆ … ┆ 2             ┆ 0             ┆ 2013-01-02    ┆ Bala Dixit    │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:10:00.0000 ┆               │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 3         ┆ 105        ┆ 1             ┆ 3       ┆ … ┆ 1             ┆ 0             ┆ 2013-01-02    ┆ Sung-Hwan     │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:15:00.0000 ┆ Hwang         │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 4         ┆ 57         ┆ 1             ┆ 4       ┆ … ┆ 3             ┆ 0             ┆ 2013-01-02    ┆ Aile Mae      │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:20:00.0000 ┆               │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
│ 5         ┆ 905        ┆ 905           ┆ 5       ┆ … ┆ 3             ┆ 0             ┆ 2013-01-02    ┆ Sara Huiting  │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 07:25:00.0000 ┆               │
│           ┆            ┆               ┆         ┆   ┆               ┆               ┆ 000           ┆               │
└───────────┴────────────┴───────────────┴─────────┴───┴───────────────┴───────────────┴───────────────┴───────────────┘

In [23]:
data_path = DATA_DIR / INGESTION_TABLES[13]
df_test = pl.scan_csv(data_path, separator=";", null_values=["", "NULL", "N/A", "null", "None"], infer_schema_length=10000).collect()

print(data_path.name)
print(df_test.shape)
print(df_test.head())
pprint(df_test.null_count().to_dicts(), sort_dicts=False)

Sales.InvoiceLines.csv
(228265, 11)
shape: (5, 11)
┌───────────────┬───────────┬─────────────┬─────────────────────┬───┬─────────┬───────────┬────────────┬───────────────┐
│ InvoiceLineID ┆ InvoiceID ┆ StockItemID ┆ Description         ┆ … ┆ TaxRate ┆ TaxAmount ┆ LineProfit ┆ ExtendedPrice │
│ ---           ┆ ---       ┆ ---         ┆ ---                 ┆   ┆ ---     ┆ ---       ┆ ---        ┆ ---           │
│ i64           ┆ i64       ┆ i64         ┆ str                 ┆   ┆ f64     ┆ f64       ┆ f64        ┆ f64           │
╞═══════════════╪═══════════╪═════════════╪═════════════════════╪═══╪═════════╪═══════════╪════════════╪═══════════════╡
│ 1             ┆ 1         ┆ 67          ┆ Ride on toy sedan   ┆ … ┆ 15.0    ┆ 345.0     ┆ 850.0      ┆ 2645.0        │
│               ┆           ┆             ┆ car (Black) …       ┆   ┆         ┆           ┆            ┆               │
│ 2             ┆ 2         ┆ 50          ┆ Developer joke mug  ┆ … ┆ 15.0    ┆ 17.55     ┆ 76.5       ┆ 134.55        │
│               ┆           ┆             ┆ - old C dev…        ┆   ┆         ┆           ┆            ┆               │
│ 3             ┆ 2         ┆ 10          ┆ USB food flash      ┆ … ┆ 15.0    ┆ 43.2      ┆ 180.0      ┆ 331.2         │
│               ┆           ┆             ┆ drive - chocola…    ┆   ┆         ┆           ┆            ┆               │
│ 4             ┆ 3         ┆ 114         ┆ Superhero action    ┆ … ┆ 15.0    ┆ 13.5      ┆ 24.0       ┆ 103.5         │
│               ┆           ┆             ┆ jacket (Blue)…      ┆   ┆         ┆           ┆            ┆               │
│ 5             ┆ 4         ┆ 206         ┆ Permanent marker    ┆ … ┆ 15.0    ┆ 38.88     ┆ 96.0       ┆ 298.08        │
│               ┆           ┆             ┆ black 5mm nib…      ┆   ┆         ┆           ┆            ┆               │
└───────────────┴───────────┴─────────────┴─────────────────────┴───┴─────────┴───────────┴────────────┴───────────────┘
[{'InvoiceLineID': 0,
  'InvoiceID': 0,
  'StockItemID': 0,
  'Description': 0,
  'PackageTypeID': 0,
  'Quantity': 0,
  'UnitPrice': 0,
  'TaxRate': 0,
  'TaxAmount': 0,
  'LineProfit': 0,
  'ExtendedPrice': 0}]

In [24]:
df_test.head()

shape: (5, 11)
┌───────────────┬───────────┬─────────────┬─────────────────────┬───┬─────────┬───────────┬────────────┬───────────────┐
│ InvoiceLineID ┆ InvoiceID ┆ StockItemID ┆ Description         ┆ … ┆ TaxRate ┆ TaxAmount ┆ LineProfit ┆ ExtendedPrice │
│ ---           ┆ ---       ┆ ---         ┆ ---                 ┆   ┆ ---     ┆ ---       ┆ ---        ┆ ---           │
│ i64           ┆ i64       ┆ i64         ┆ str                 ┆   ┆ f64     ┆ f64       ┆ f64        ┆ f64           │
╞═══════════════╪═══════════╪═════════════╪═════════════════════╪═══╪═════════╪═══════════╪════════════╪═══════════════╡
│ 1             ┆ 1         ┆ 67          ┆ Ride on toy sedan   ┆ … ┆ 15.0    ┆ 345.0     ┆ 850.0      ┆ 2645.0        │
│               ┆           ┆             ┆ car (Black) …       ┆   ┆         ┆           ┆            ┆               │
│ 2             ┆ 2         ┆ 50          ┆ Developer joke mug  ┆ … ┆ 15.0    ┆ 17.55     ┆ 76.5       ┆ 134.55        │
│               ┆           ┆             ┆ - old C dev…        ┆   ┆         ┆           ┆            ┆               │
│ 3             ┆ 2         ┆ 10          ┆ USB food flash      ┆ … ┆ 15.0    ┆ 43.2      ┆ 180.0      ┆ 331.2         │
│               ┆           ┆             ┆ drive - chocola…    ┆   ┆         ┆           ┆            ┆               │
│ 4             ┆ 3         ┆ 114         ┆ Superhero action    ┆ … ┆ 15.0    ┆ 13.5      ┆ 24.0       ┆ 103.5         │
│               ┆           ┆             ┆ jacket (Blue)…      ┆   ┆         ┆           ┆            ┆               │
│ 5             ┆ 4         ┆ 206         ┆ Permanent marker    ┆ … ┆ 15.0    ┆ 38.88     ┆ 96.0       ┆ 298.08        │
│               ┆           ┆             ┆ black 5mm nib…      ┆   ┆         ┆           ┆            ┆               │
└───────────────┴───────────┴─────────────┴─────────────────────┴───┴─────────┴───────────┴────────────┴───────────────┘

In [25]:
print(df_test.item)
print(df_test.select(pl.len()))

<bound method DataFrame.item of shape: (228_265, 11)
┌───────────────┬───────────┬─────────────┬─────────────────────┬───┬─────────┬───────────┬────────────┬───────────────┐
│ InvoiceLineID ┆ InvoiceID ┆ StockItemID ┆ Description         ┆ … ┆ TaxRate ┆ TaxAmount ┆ LineProfit ┆ ExtendedPrice │
│ ---           ┆ ---       ┆ ---         ┆ ---                 ┆   ┆ ---     ┆ ---       ┆ ---        ┆ ---           │
│ i64           ┆ i64       ┆ i64         ┆ str                 ┆   ┆ f64     ┆ f64       ┆ f64        ┆ f64           │
╞═══════════════╪═══════════╪═════════════╪═════════════════════╪═══╪═════════╪═══════════╪════════════╪═══════════════╡
│ 1             ┆ 1         ┆ 67          ┆ Ride on toy sedan   ┆ … ┆ 15.0    ┆ 345.0     ┆ 850.0      ┆ 2645.0        │
│               ┆           ┆             ┆ car (Black) …       ┆   ┆         ┆           ┆            ┆               │
│ 2             ┆ 2         ┆ 50          ┆ Developer joke mug  ┆ … ┆ 15.0    ┆ 17.55     ┆ 76.5       ┆ 134.55        │
│               ┆           ┆             ┆ - old C dev…        ┆   ┆         ┆           ┆            ┆               │
│ 3             ┆ 2         ┆ 10          ┆ USB food flash      ┆ … ┆ 15.0    ┆ 43.2      ┆ 180.0      ┆ 331.2         │
│               ┆           ┆             ┆ drive - chocola…    ┆   ┆         ┆           ┆            ┆               │
│ 4             ┆ 3         ┆ 114         ┆ Superhero action    ┆ … ┆ 15.0    ┆ 13.5      ┆ 24.0       ┆ 103.5         │
│               ┆           ┆             ┆ jacket (Blue)…      ┆   ┆         ┆           ┆            ┆               │
│ 5             ┆ 4         ┆ 206         ┆ Permanent marker    ┆ … ┆ 15.0    ┆ 38.88     ┆ 96.0       ┆ 298.08        │
│               ┆           ┆             ┆ black 5mm nib…      ┆   ┆         ┆           ┆            ┆               │
│ …             ┆ …         ┆ …           ┆ …                   ┆ … ┆ …       ┆ …         ┆ …          ┆ …             │
│ 228261        ┆ 70510     ┆ 59          ┆ RC toy sedan car    ┆ … ┆ 15.0    ┆ 22.5      ┆ 75.0       ┆ 172.5         │
│               ┆           ┆             ┆ with remote c…      ┆   ┆         ┆           ┆            ┆               │
│ 228262        ┆ 70510     ┆ 2           ┆ USB rocket launcher ┆ … ┆ 15.0    ┆ 3.75      ┆ 15.5       ┆ 28.75         │
│               ┆           ┆             ┆ (Gray)              ┆   ┆         ┆           ┆            ┆               │
│ 228263        ┆ 70510     ┆ 102         ┆ Alien officer       ┆ … ┆ 15.0    ┆ 47.25     ┆ 162.0      ┆ 362.25        │
│               ┆           ┆             ┆ hoodie (Black) X…   ┆   ┆         ┆           ┆            ┆               │
│ 228264        ┆ 70510     ┆ 170         ┆ 20 mm Anti static   ┆ … ┆ 15.0    ┆ 612.0     ┆ 1880.0     ┆ 4692.0        │
│               ┆           ┆             ┆ bubble wrap …       ┆   ┆         ┆           ┆            ┆               │
│ 228265        ┆ 70510     ┆ 130         ┆ Furry gorilla with  ┆ … ┆ 15.0    ┆ 38.4      ┆ 192.0      ┆ 294.4         │
│               ┆           ┆             ┆ big eyes sl…        ┆   ┆         ┆           ┆            ┆               │
└───────────────┴───────────┴─────────────┴─────────────────────┴───┴─────────┴───────────┴────────────┴───────────────┘>
shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 228265 │
└────────┘

In [26]:
data_path = DATA_DIR / INGESTION_TABLES[13]
total_rows = (
    pl.scan_csv(data_path, ignore_errors=True)
    .select(pl.len())
    .collect()
    .item()
)

total_rows

228265